Repository grote/Transportr, pull requests merged in 2024-01, with the labels that each got.

#901 Re-add VRS network
  app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-eo/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-eu/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-nb/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt-rBR/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  artwork/networks/network_vrs_logo.svg
Labels: bug 🐞, coverage 🗺️, cla-signed ✔️, priority 🚨️

#904 Reenable Wiener Linien provider
  app/src/main/java/de/grobox/transportr/networks/TransportNetworks.kt
Labels: coverage 🗺️, priority 🚨️

#893 Fix timePicker minutes always set to current time
  app/src/main/java/de/grobox/transportr/ui/TimeDateFragment.kt
Labels: cla-signed ✔️

#912 Fix location provider
  app/src/main/java/de/grobox/transportr/map/PositionController.kt
Labels: bug 🐞, cla-signed ✔️, priority 🚨️

#914 Fix some theming-related issues
  app/src/main/java/de/grobox/transportr/settings/SettingsFragment.kt
  app/src/main/java/de/grobox/transportr/settings/SettingsManager.kt
  app/src/main/res/xml/preferences.xml
Labels: cla-signed ✔️

#918 Release 2.2.1
  app/build.gradle
  app/src/main/res/xml/changelog_master.xml
  fastlane/metadata/android/en-US/changelogs/125.txt
Labels: cla-signed ✔️
